services:
  valkey:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data
    command: ["--save", "60", "1", "--loglevel", "warning"]
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mcpserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
      - VALKEY_USERNAME=
      - VALKEY_PASSWORD=
      - SERVER_PORT=8080
    depends_on:
      valkey:
        condition: service_healthy
    restart: unless-stopped

volumes:
  valkey-data:
