version: '3'

services:
  valkey:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data
    command: ["--save", "60", "1", "--loglevel", "warning"]
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # STDIO-only MCP server
  mcpserver-stdio:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
      - VALKEY_USERNAME=
      - VALKEY_PASSWORD=
      - ENABLE_SSE=false
      - ENABLE_STREAMABLE_HTTP=false
      - ENABLE_STDIO=true
      - STDIO_ERROR_LOG=true
    depends_on:
      valkey:
        condition: service_healthy
    stdin_open: true  # Required for STDIO transport
    tty: true         # Allocate a pseudo-TTY

volumes:
  valkey-data:
